# Generated by Django 3.0.6 on 2020-06-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/fish')),
            ],
        ),
    ]
