# Generated by Django 3.0.6 on 2020-06-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_desc', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('food_price', models.IntegerField()),
                ('food_image', models.ImageField(upload_to='static/food')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='static/product')),
            ],
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='desc',
            new_name='fish_desc',
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='image',
            new_name='fish_image',
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='name',
            new_name='fish_name',
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='price',
            new_name='fish_price',
        ),
    ]
