# Generated by Django 3.0.6 on 2020-07-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200626_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_desc', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('item_catagory', models.CharField(max_length=300)),
                ('item_price', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='fish',
            name='fish_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
