# Generated by Django 2.2.15 on 2020-08-14 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200630_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
