# Generated by Django 2.2.15 on 2020-09-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='number',
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=111),
        ),
    ]
